### ISSUE TITLE
DBスキーマ定義

### ISSUE THREAD

**Issue by Taiki130** [chaos-tech/training-note#4]

**Comment by hayura-k** [comment]
### users
| 論理カラム | データ型     | 制約             |  |
| ---------- | ------------ | ---------------- | --|
| id         | bigint       | not null |  PK |
| uid        | varchar(255) | not null         |  |
| nickname   | varchar(255) | not null         |  |

### training_menu
| 論理カラム | データ型     | 制約             |  |
| ---------- | ------------ | ---------------- | --|
| id         | bigint       | not null | PK |
| uid        | varchar(255) | not null         |  |
| nickname   | varchar(255) | not null         |  |
| uid        | varchar(255) | not null         |  |
| nickname   | varchar(255) | not null         |  |
| uid        | varchar(255) | not null         |  |
| nickname   | varchar(255) | not null         |  |

### training_menu_log
| 論理カラム | データ型     | 制約             |  |
| ---------- | ------------ | ---------------- | --|
| id         | bigint       | not null |  PK |
| uid        | varchar(255) | not null         |  |
| nickname   | varchar(255) | not null         |  |
| uid        | varchar(255) | not null         |  |
| nickname   | varchar(255) | not null         |  |
| uid        | varchar(255) | not null         |  |
| nickname   | varchar(255) | not null         |  |

**Comment by Taiki130** [comment]
set数はintじゃいかんのか？

**Comment by Taiki130** [comment]
weightには 12.5とかの浮動小数点も入るかも

**Comment by hayura-k** [comment]
なんでsetをvarcharにしてたんだ、、

weightをrealにchange！

**Comment by kagunyan25** [comment]
メニュー名がないですけど！！！！！

**Comment by kagunyan25** [comment]
はよDBとAPI作れ！
